title: Seeding, streaming and sharing... 
author: 
  name: giovanni-savino
description: A collection of small hints about automation, integration, DevOps and streaming ideas
theme: jekyll-theme-minimal
